teamcovey/covey

Gulpfile.js, package.json, specs/server/serverExampleSpec.js
Make sure you run npm install after rebasing!
=> Make npm test run gulp test

package.json, server/collections/cars.js, server/collections/coveys.js, server/collections/resources.js, server/collections/users.js, server/config/config.js, server/config/server-config.js, server/models/car.js, server/models/covey.js, server/models/resource.js, server/models/user.js, server/routers/router-helpers.js, server/routers/router.js, specs/server/serverExampleSpec.js
Lots of code to handle the backend interaction of the express server and psql database reads and writes.  Lots of knex sql vs bookshelf.
=> Closes #56: Routes and Request handlers and DB oh my!

server/routers/router-coveys.js, server/routers/router-helpers.js, server/routers/router-resources.js, server/routers/router-rides.js, server/routers/router.js
Added cleanup to removing attendee and updating rides and supplies
=> Update plus remove

.travis.yml, server/routers/router-coveys.js
had to re-add the resource update.
=> fixing remove attendee

server/routers/router-users.js
correction for my previous pull
=> needed to fix two way relation instead of one way relation twice.

server/routers/router-coveys.js, server/routers/router-resources.js, server/routers/router-rides.js, server/routers/router-users.js
Makes it cleaner to use and process on the client side.
=> Better union of riders/supplies with rides/resources

.travis.yml, server/routers/router-coveys.js, server/routers/router-users.js, server/routers/router.js, specs/server/serverExampleSpec.js
added more robust testing for server side functions
=> git fixed some typos for getcovey

specs/server/serverExampleSpec.js
=> more testing on attendees etc.

client/app.js, client/features/friends/controllers/friendsController.js, client/features/friends/directives/friendsDirective.js, client/features/friends/services/friendsService.js, client/features/friends/views/friends.html, client/features/friends/views/myfriends.html, client/index.html, server/config/passport.js, server/routers/router-users.js, server/routers/router.js
Basic search for friends and adding and removing friends.
=> Friends first

client/features/friends/controllers/friendsController.js, karma.conf.js, server/routers/router-helpers.js, server/routers/router-users.js, specs/client/friendSpec.js
=> Friends test

server/routers/router-users.js
fixed updating user to only change new fields.
=> Update user clean

bower.json, client/app.js, client/features/chat/controllers/chatController.js, client/features/chat/services/chatService.js, client/features/chat/views/chatView.html, client/features/covey/directives/coveyDirectives.js, client/index.html, client/styles/covey.css, karma.conf.js, server/routers/router-users.js, server/routers/router.js
Added chat.  defaults to unique room based on coveyId and defaults username to users first and last initial.
=> Firebase chat

client/features/friends/views/myfriends.html, server/routers/router-users.js
cleaning up friends usage and appearance.
=> Friends plus

client/features/friends/controllers/friendsController.js, client/features/friends/views/myfriends.html, client/styles/friends.css
=> added a close search and a bit of styling around searching for friends.

client/features/friends/controllers/friendsController.js, client/features/friends/views/myfriends.html, client/styles/friends.css
closes #183 
closes #166 
better handling of friends addition and removal.
=> Friends end.  better styling and handling

client/features/attendees/controllers/attendeesController.js, server/config/passport.js
Previous implementation was passing an undefined user id in the http request
closes #196
=> Fix bug in add/remove attendees functionality.

client/features/covey/controllers/coveyController.js, client/features/covey/views/detailsView.html
closes #190 
closes #188 
Using date format swapping
=> added better styling for date editing in edit covey

Dockerfile
=> re add gulp

client/features/friends/views/myfriends.html, client/styles/friends.css
wanted to have consistent behavior between friends and coveys
=> added an icon and different styling for removing friends

client/features/rides/controllers/ridesController.js, client/features/rides/services/ridesService.js
=> mmm sockets

client/features/rides/controllers/ridesController.js, client/features/rides/services/ridesService.js
=> remove log messages.  end of testing.
